repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: end-of-file-fixer
      exclude: '^LICENSE$'
    - id: check-yaml
    - id: check-added-large-files

- repo: https://codeberg.org/vifon/pre-commit-hooks
  rev: 779f29ebd525d11923aa3578b3a94a13bbef1249
  hooks:
    - id: shellcheck
    - id: elisp-check-parens
    - id: elisp-checkdoc
      exclude: '^tmsu-tests.el$'
    - id: elisp-package-lint
      args: [--main-file, tmsu.el]
      files: |
        (?x)^(
        tmsu\.el|
        tmsu-[^/]+\.el
        )$
      exclude: '^tmsu-tests.el$'
    - id: elisp-package-lint
      name: Run Emacs package-lint (org-mode integration)
      args: [--main-file, ol-tmsu.el]
      files: '^ol-tmsu\.el$'
    - id: no-elc

- repo: https://github.com/vifon/elisp-lint
  rev: 7d9ec0f5141d2f3e4c0fc890d40fceca81f8eb6f
  hooks:
    - id: elisp-lint
      args: [--main-file, tmsu.el]
      files: |
        (?x)^(
        tmsu\.el|
        tmsu-[^/]+\.el
        )$
      exclude: '^tmsu-tests.el$'
    - id: elisp-lint
      name: Run Emacs elisp-lint (org-mode integration)
      args: [--main-file, ol-tmsu.el]
      files: '^ol-tmsu\.el$'
    - id: elisp-lint-cleanup

- repo: local
  hooks:
    - id: unittests
      name: Run unittests
      language: system
      entry: >
        emacs -Q --batch
        -L . -l tmsu-tests.el
        -f ert-run-tests-batch-and-exit
      pass_filenames: false
